version: '3.1'

services:

  stats-server:
    container_name: ewm-stats-service
    build: ewm-stats-service/stats-service
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - WEB_PORT=9090
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_URL=http://stats-server:9090
      - DB_NAME=stats
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-db:
    container_name: ewm-stats-db
    image: postgres:14-alpine
    volumes:
      - stats-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    container_name: ewm-main-service
    build: ewm-main-service
    depends_on:
      ewm-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - WEB_PORT=8080
      - STATS_SERVER_URL=http://stats-server:9090
      - DB_NAME=ewm
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    container_name: ewm-main-db
    image: postgres:14-alpine
    volumes:
      - ewm-volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  stats-volume:
  ewm-volume:
